//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PhotoUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Images = new HashSet<Image>();
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        [DisplayName("Username")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "can not be null")]
        [MinLength(6, ErrorMessage = "Username too short ( 6 chars )")]
        public string username { get; set; }
        [DisplayName("Password")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password can not be null")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Password too short ( 6 chars )")]
        public string password { get; set; }
        public string salt { get; set; }
        [DisplayName("First Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "First Name can not be null")]
        public string firstName { get; set; }
        [DisplayName("Last Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last Name can not be null")]
        public string lastName { get; set; }
        [DisplayName("Address")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Address can not be null")]
        public string address { get; set; }
        [DisplayName("Email")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email can not be null")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [DisplayName("Phone")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Phone can not be null")]
        public string phone { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        [DisplayName("Payment Method")]
        public int Payment_Method_id { get; set; }
        public int status { get; set; }
    
        public virtual Payment_Method Payment_Method { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
