//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public Order_Detail()
        {
        }

        public Order_Detail(Image image, int quantity, decimal unitPrice, int priceId)
        {
            this.Image = image;
            this.quantity = quantity;
            this.unitPrice = unitPrice;
            this.Price_id = priceId;
        }

        public int id { get; set; }
        public int Order_id { get; set; }
        public int Image_id { get; set; }
        public int Price_id { get; set; }
        public int quantity { get; set; }
        public decimal unitPrice { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Order Order { get; set; }
        public virtual Price Price { get; set; }
    }
}
